//! Queries a `GraphStore` and renders onboarding/engineering documentation as
//! Markdown — Codebrain-3 ("generate engineering documentation and onboarding
//! material directly from the indexed graph"). This is the automated version of
//! the engineering-doc PDF produced manually earlier in this project.

use std::path::Path;

use agentops_graph::{EdgeRelation, GraphStore, NodeKind};

/// Renders a full onboarding/engineering doc: repo stats, a ranked file/symbol
/// map, and every gotcha node together with the symbol it's edge-connected to
/// (Codebrain-2's payoff — this is where a prior gotcha actually resurfaces for
/// whoever is reading the doc).
///
/// `ranked_paths` should be the output of `agentops_scanner::rank_files`,
/// highest-ranked first — this crate doesn't recompute ranking itself, since
/// that's the scanner's job (see the plan's crate-boundary design).
pub fn render_onboarding_doc(store: &dyn GraphStore, repo_name: &str, ranked_paths: &[std::path::PathBuf]) -> anyhow::Result<String> {
    let all_symbols = store.nodes_by_kind(NodeKind::Symbol)?;
    let all_files = store.nodes_by_kind(NodeKind::File)?;
    let all_gotchas = store.nodes_by_kind(NodeKind::Gotcha)?;
    let all_decisions = store.nodes_by_kind(NodeKind::Decision)?;

    let mut out = String::new();
    out.push_str(&format!("# {repo_name} — engineering overview\n\n"));
    out.push_str("_Generated by agentops-docgen from the indexed code graph._\n\n");

    out.push_str("## Stats\n\n");
    out.push_str(&format!(
        "- Files indexed: {}\n- Symbols indexed: {}\n- Gotchas recorded: {}\n- Decisions recorded: {}\n\n",
        all_files.len(),
        all_symbols.len(),
        all_gotchas.len(),
        all_decisions.len(),
    ));

    out.push_str("## Repository map\n\n");
    out.push_str("Files ranked by centrality in the dependency graph (most-referenced first):\n\n");

    for path in ranked_paths {
        let path_str = path.to_string_lossy();
        let symbols_in_file: Vec<_> = all_symbols
            .iter()
            .filter(|s| s.path.as_deref() == Some(path_str.as_ref()))
            .collect();

        out.push_str(&format!("### `{path_str}`\n\n"));
        if symbols_in_file.is_empty() {
            out.push_str("_(no symbols extracted for this file)_\n\n");
            continue;
        }
        for symbol in symbols_in_file {
            let name = symbol.name.as_deref().unwrap_or("<anonymous>");
            out.push_str(&format!(
                "- `{name}` (lines {}-{})",
                symbol.start_line.unwrap_or(0),
                symbol.end_line.unwrap_or(0),
            ));

            let gotchas = gotchas_affecting(store, symbol.id)?;
            if !gotchas.is_empty() {
                out.push_str(&format!(" — **{} known gotcha(s) apply**", gotchas.len()));
            }
            out.push('\n');
        }
        out.push('\n');
    }

    if !all_gotchas.is_empty() {
        out.push_str("## Known gotchas\n\n");
        out.push_str("Every recorded workaround/issue, and the exact symbol it affects — an agent working on that symbol should read this first.\n\n");
        for gotcha in &all_gotchas {
            let name = gotcha.name.as_deref().unwrap_or("(untitled)");
            let text = gotcha.content.as_deref().unwrap_or("");
            out.push_str(&format!("**{name}**\n\n{text}\n\n"));

            let edges = store.edges_from(gotcha.id)?;
            for edge in edges.iter().filter(|e| e.relation == EdgeRelation::Affects) {
                if let Some(target) = store.get_node(edge.dst_id)? {
                    let target_name = target.name.as_deref().unwrap_or("<unknown>");
                    let target_path = target.path.as_deref().unwrap_or("");
                    out.push_str(&format!("- Affects: `{target_name}` in `{target_path}`\n"));
                }
            }
            out.push('\n');
        }
    }

    Ok(out)
}

fn gotchas_affecting(store: &dyn GraphStore, symbol_id: i64) -> anyhow::Result<Vec<agentops_graph::Edge>> {
    Ok(store
        .edges_to(symbol_id)?
        .into_iter()
        .filter(|e| e.relation == EdgeRelation::Affects)
        .collect())
}

/// Writes the rendered doc to `path` (typically `<repo>/repo-map.md`).
pub fn write_to_file(content: &str, path: &Path) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use agentops_graph::{NewNode, SqliteGraphStore};
    use std::path::PathBuf;

    #[test]
    fn renders_stats_ranked_files_and_linked_gotchas() {
        let store = SqliteGraphStore::open_in_memory().unwrap();

        let file_path = "src/auth.rs".to_string();
        store
            .add_node(NewNode {
                kind: NodeKind::File,
                repo: "demo".into(),
                path: Some(file_path.clone()),
                name: None,
                start_line: None,
                end_line: None,
                content: None,
            })
            .unwrap();

        let symbol_id = store
            .add_node(NewNode {
                kind: NodeKind::Symbol,
                repo: "demo".into(),
                path: Some(file_path.clone()),
                name: Some("verify_token".into()),
                start_line: Some(10),
                end_line: Some(25),
                content: Some("fn verify_token() {}".into()),
            })
            .unwrap();

        let gotcha_id = store
            .add_node(NewNode {
                kind: NodeKind::Gotcha,
                repo: "demo".into(),
                path: None,
                name: Some("token-expiry-off-by-one".into()),
                start_line: None,
                end_line: None,
                content: Some("Expiry check was off by one day.".into()),
            })
            .unwrap();
        store.add_edge(gotcha_id, symbol_id, EdgeRelation::Affects).unwrap();

        let doc = render_onboarding_doc(&store, "demo", &[PathBuf::from(&file_path)]).unwrap();

        assert!(doc.contains("Symbols indexed: 1"));
        assert!(doc.contains("Gotchas recorded: 1"));
        assert!(doc.contains("src/auth.rs"));
        assert!(doc.contains("verify_token"));
        assert!(doc.contains("known gotcha(s) apply"));
        assert!(doc.contains("token-expiry-off-by-one"));
        assert!(doc.contains("Affects: `verify_token` in `src/auth.rs`"));
    }
}
