//! Queries a `GraphStore` and renders onboarding/engineering documentation as
//! Markdown — Codebrain-3 ("generate engineering documentation and onboarding
//! material directly from the indexed graph"). This is the automated version of
//! the engineering-doc PDF produced manually earlier in this project.

use std::path::Path;

use agentops_graph::{EdgeRelation, GraphStore, NodeKind};

/// Renders a full onboarding/engineering doc: repo stats, a ranked file/symbol
/// map, and every gotcha node together with the symbol it's edge-connected to
/// (Codebrain-2's payoff — this is where a prior gotcha actually resurfaces for
/// whoever is reading the doc).
///
/// `ranked_paths` should be the output of `agentops_scanner::rank_files`,
/// highest-ranked first — this crate doesn't recompute ranking itself, since
/// that's the scanner's job (see the plan's crate-boundary design).
pub fn render_onboarding_doc(store: &dyn GraphStore, repo_name: &str, ranked_paths: &[std::path::PathBuf]) -> anyhow::Result<String> {
    let all_symbols = store.nodes_by_kind(repo_name, NodeKind::Symbol)?;
    let all_files = store.nodes_by_kind(repo_name, NodeKind::File)?;
    let all_gotchas = store.nodes_by_kind(repo_name, NodeKind::Gotcha)?;
    let all_decisions = store.nodes_by_kind(repo_name, NodeKind::Decision)?;

    let mut out = String::new();
    out.push_str(&format!("# {repo_name} — engineering overview\n\n"));
    out.push_str("_Generated by agentops-docgen from the indexed code graph._\n\n");

    out.push_str("## Stats\n\n");
    out.push_str(&format!(
        "- Files indexed: {}\n- Symbols indexed: {}\n- Gotchas recorded: {}\n- Decisions recorded: {}\n\n",
        all_files.len(),
        all_symbols.len(),
        all_gotchas.len(),
        all_decisions.len(),
    ));

    out.push_str("## Repository map\n\n");
    out.push_str("Files ranked by centrality in the dependency graph (most-referenced first):\n\n");

    for path in ranked_paths {
        let path_str = path.to_string_lossy();
        let symbols_in_file: Vec<_> = all_symbols.iter().filter(|s| s.path.as_deref() == Some(path_str.as_ref())).collect();

        out.push_str(&format!("### `{path_str}`\n\n"));
        if symbols_in_file.is_empty() {
            out.push_str("_(no symbols extracted for this file)_\n\n");
            continue;
        }
        for symbol in symbols_in_file {
            let name = symbol.name.as_deref().unwrap_or("<anonymous>");
            out.push_str(&format!("- `{name}` (lines {}-{})", symbol.start_line.unwrap_or(0), symbol.end_line.unwrap_or(0)));

            let gotchas = gotchas_affecting(store, repo_name, symbol.id)?;
            if !gotchas.is_empty() {
                out.push_str(&format!(" — **{} known gotcha(s) apply**", gotchas.len()));
            }
            out.push('\n');
        }
        out.push('\n');
    }

    if !all_gotchas.is_empty() {
        out.push_str("## Known gotchas\n\n");
        out.push_str("Every recorded workaround/issue, and the exact symbol it affects — an agent working on that symbol should read this first.\n\n");
        render_notes(&mut out, store, repo_name, &all_gotchas)?;
    }

    if !all_decisions.is_empty() {
        out.push_str("## Decisions\n\n");
        out.push_str("Every recorded design decision, and the exact symbol it's tied to — the \"why\" behind code that might otherwise look arbitrary.\n\n");
        render_notes(&mut out, store, repo_name, &all_decisions)?;
    }

    Ok(out)
}

/// Shared rendering for gotcha and decision nodes — both are just "a note
/// edge-connected to a symbol," differing only in which section they land in.
fn render_notes(out: &mut String, store: &dyn GraphStore, repo_name: &str, notes: &[agentops_graph::Node]) -> anyhow::Result<()> {
    for note in notes {
        let name = note.name.as_deref().unwrap_or("(untitled)");
        let text = note.content.as_deref().unwrap_or("");
        out.push_str(&format!("**{name}**\n\n{text}\n\n"));

        let edges = store.edges_from(repo_name, note.id)?;
        for edge in edges.iter().filter(|e| e.relation == EdgeRelation::Affects) {
            if let Some(target) = store.get_node(repo_name, edge.dst_id)? {
                let target_name = target.name.as_deref().unwrap_or("<unknown>");
                let target_path = target.path.as_deref().unwrap_or("");
                out.push_str(&format!("- Affects: `{target_name}` in `{target_path}`\n"));
            }
        }
        out.push('\n');
    }
    Ok(())
}

fn gotchas_affecting(store: &dyn GraphStore, repo_name: &str, symbol_id: i64) -> anyhow::Result<Vec<agentops_graph::Edge>> {
    Ok(store.edges_to(repo_name, symbol_id)?.into_iter().filter(|e| e.relation == EdgeRelation::Affects).collect())
}

/// Writes the rendered doc to `path` (typically `<repo>/repo-map.md`).
pub fn write_to_file(content: &str, path: &Path) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use agentops_graph::{NewNode, SqliteGraphStore};
    use std::path::PathBuf;

    fn node(kind: NodeKind, path: Option<&str>, name: Option<&str>, start_line: Option<i64>, end_line: Option<i64>, content: Option<&str>) -> NewNode {
        NewNode {
            kind,
            repo: "demo".into(),
            path: path.map(String::from),
            name: name.map(String::from),
            container: None,
            start_line,
            end_line,
            content: content.map(String::from),
        }
    }

    #[test]
    fn renders_stats_ranked_files_and_linked_gotchas() {
        let store = SqliteGraphStore::open_in_memory().unwrap();

        let file_path = "src/auth.rs";
        store.add_node(node(NodeKind::File, Some(file_path), None, None, None, None)).unwrap();

        let symbol_id = store.add_node(node(NodeKind::Symbol, Some(file_path), Some("verify_token"), Some(10), Some(25), Some("fn verify_token() {}"))).unwrap();

        let gotcha_id = store.add_node(node(NodeKind::Gotcha, None, Some("token-expiry-off-by-one"), None, None, Some("Expiry check was off by one day."))).unwrap();
        store.add_edge("demo", gotcha_id, symbol_id, EdgeRelation::Affects).unwrap();

        let doc = render_onboarding_doc(&store, "demo", &[PathBuf::from(file_path)]).unwrap();

        assert!(doc.contains("Symbols indexed: 1"));
        assert!(doc.contains("Gotchas recorded: 1"));
        assert!(doc.contains("src/auth.rs"));
        assert!(doc.contains("verify_token"));
        assert!(doc.contains("known gotcha(s) apply"));
        assert!(doc.contains("token-expiry-off-by-one"));
        assert!(doc.contains("Affects: `verify_token` in `src/auth.rs`"));
    }

    #[test]
    fn renders_a_decisions_section_alongside_gotchas() {
        let store = SqliteGraphStore::open_in_memory().unwrap();

        let symbol_id =
            store.add_node(node(NodeKind::Symbol, Some("src/keys.rs"), Some("generate_deploy_keypair_for_repo"), Some(1), Some(5), Some("fn generate_deploy_keypair_for_repo() {}"))).unwrap();

        let decision_id =
            store.add_node(node(NodeKind::Decision, None, Some("passphrase-not-yet-kms-backed"), None, None, Some("EnvSecretsProvider is fine for self-hosted, not for multi-tenant."))).unwrap();
        store.add_edge("demo", decision_id, symbol_id, EdgeRelation::Affects).unwrap();

        let doc = render_onboarding_doc(&store, "demo", &[PathBuf::from("src/keys.rs")]).unwrap();

        assert!(doc.contains("## Decisions"));
        assert!(doc.contains("passphrase-not-yet-kms-backed"));
        assert!(doc.contains("Affects: `generate_deploy_keypair_for_repo` in `src/keys.rs`"));
    }

    /// Regression test for the repo-scoping fix this port made over `main`'s
    /// original (unscoped) version: a gotcha recorded in a different repo
    /// must never leak into this repo's doc.
    #[test]
    fn does_not_leak_nodes_across_repos() {
        let store = SqliteGraphStore::open_in_memory().unwrap();
        let mut other_repo_gotcha = node(NodeKind::Gotcha, None, Some("other-repo-gotcha"), None, None, Some("belongs to a different repo"));
        other_repo_gotcha.repo = "other-repo".into();
        store.add_node(other_repo_gotcha).unwrap();

        let doc = render_onboarding_doc(&store, "demo", &[]).unwrap();
        assert!(!doc.contains("other-repo-gotcha"));
        assert!(doc.contains("Gotchas recorded: 0"));
    }
}
