import { describe, expect, it } from "vitest";
import { parseDocgenMarkdown } from "./docgen-doc";

// Mirrors agentops-docgen::render_onboarding_doc's exact real output shape
// (agentops-core/crates/agentops-docgen/src/lib.rs) -- not a hand-invented
// fixture, copied structurally from that Rust source and its own tests.
const FIXTURE = `# demo — engineering overview

_Generated by agentops-docgen from the indexed code graph._

## Stats

- Files indexed: 2
- Symbols indexed: 2
- Gotchas recorded: 1
- Decisions recorded: 1

## Repository map

Files ranked by centrality in the dependency graph (most-referenced first):

### \`src/auth.rs\`

- \`verify_token\` (lines 1-5) — **1 known gotcha(s) apply**

### \`src/empty.rs\`

_(no symbols extracted for this file)_

## Known gotchas

Every recorded workaround/issue, and the exact symbol it affects — an agent working on that symbol should read this first.

**token-expiry-off-by-one**

## Context

Expiry check was off by one day. See ## Decisions below for the fix rationale (a note's own body prose, not a real section boundary).

### Root Cause

Timezone handling bug.

- Affects: \`verify_token\` in \`src/auth.rs\`

## Decisions

Every recorded design decision, and the exact symbol it's tied to — the "why" behind code that might otherwise look arbitrary.

**passphrase-not-yet-kms-backed**

EnvSecretsProvider is fine for self-hosted, not for multi-tenant.

- Affects: \`generate_deploy_keypair_for_repo\` in \`src/keys.rs\`

`;

describe("parseDocgenMarkdown", () => {
  it("extracts title/subtitle from the intro", () => {
    const doc = parseDocgenMarkdown(FIXTURE)!;
    expect(doc.title).toBe("demo — engineering overview");
    expect(doc.subtitle).toContain("Generated by agentops-docgen");
  });

  it("parses stats bullets into label/value pairs", () => {
    const doc = parseDocgenMarkdown(FIXTURE)!;
    expect(doc.stats).toEqual([
      { label: "Files indexed", value: "2" },
      { label: "Symbols indexed", value: "2" },
      { label: "Gotchas recorded", value: "1" },
      { label: "Decisions recorded", value: "1" },
    ]);
  });

  it("parses each file's symbols including gotcha counts", () => {
    const doc = parseDocgenMarkdown(FIXTURE)!;
    expect(doc.files).toHaveLength(2);
    expect(doc.files[0]).toEqual({
      path: "src/auth.rs",
      symbols: [{ name: "verify_token", startLine: 1, endLine: 5, gotchaCount: 1 }],
    });
  });

  it("handles a file with no extracted symbols as an empty symbol list, not an error", () => {
    const doc = parseDocgenMarkdown(FIXTURE)!;
    expect(doc.files[1]).toEqual({ path: "src/empty.rs", symbols: [] });
  });

  it("parses gotcha notes with their affected-symbol chips", () => {
    const doc = parseDocgenMarkdown(FIXTURE)!;
    expect(doc.gotchas).toHaveLength(1);
    expect(doc.gotchas[0].title).toBe("token-expiry-off-by-one");
    expect(doc.gotchas[0].affects).toEqual([{ name: "verify_token", path: "src/auth.rs" }]);
  });

  it("does not let a note's own internal ##/### headings (real user-authored content) get misread as top-level docgen section boundaries", () => {
    const doc = parseDocgenMarkdown(FIXTURE)!;
    // The doc title/stats must reflect the real top of the document, not
    // whatever heading-looking text appears deep inside a note's body.
    expect(doc.title).toBe("demo — engineering overview");
    expect(doc.stats.find((s) => s.label === "Files indexed")?.value).toBe("2");
    // The note's internal headings and the literal string "## Decisions"
    // inside its own prose must stay part of that note's body, not trigger
    // an early section transition.
    expect(doc.gotchas[0].body).toContain("## Context");
    expect(doc.gotchas[0].body).toContain("### Root Cause");
    expect(doc.gotchas[0].body).toContain("Timezone handling bug.");
    // And the real "## Decisions" section still parses correctly afterward.
    expect(doc.decisions).toHaveLength(1);
    expect(doc.decisions[0].title).toBe("passphrase-not-yet-kms-backed");
  });

  it("parses decision notes the same way as gotchas, into a separate list", () => {
    const doc = parseDocgenMarkdown(FIXTURE)!;
    expect(doc.decisions).toHaveLength(1);
    expect(doc.decisions[0].title).toBe("passphrase-not-yet-kms-backed");
    expect(doc.decisions[0].affects).toEqual([{ name: "generate_deploy_keypair_for_repo", path: "src/keys.rs" }]);
  });

  it("returns null for markdown that isn't agentops-docgen's shape, so callers can fall back to raw rendering", () => {
    expect(parseDocgenMarkdown("# Just a random doc\n\nSome prose.\n")).toBeNull();
  });
});
