import { describe, expect, it } from "vitest";
import { extractToc, slugify } from "./markdown-toc";

describe("slugify", () => {
  it("lowercases, hyphenates spaces, and strips punctuation", () => {
    expect(slugify("Repository map")).toBe("repository-map");
    expect(slugify("`src/lib.rs`")).toBe("srclibrs");
  });
});

describe("extractToc", () => {
  // Real shape of agentops-docgen's output (see agentops-core/crates/agentops-docgen).
  const markdown = `# docbrain-graph — engineering overview

_Generated by agentops-docgen from the indexed code graph._

## Stats

- Files indexed: 1

## Repository map

Files ranked by centrality:

### \`src/lib.rs\`

- \`TenantContext\` (lines 24-27)

## Known gotchas

No gotchas recorded.

## Decisions

No decisions recorded.
`;

  it("extracts h1/h2/h3 headings in document order with the right levels", () => {
    const toc = extractToc(markdown);
    expect(toc.map((e) => [e.level, e.text])).toEqual([
      [1, "docbrain-graph — engineering overview"],
      [2, "Stats"],
      [2, "Repository map"],
      [3, "`src/lib.rs`"],
      [2, "Known gotchas"],
      [2, "Decisions"],
    ]);
  });

  it("disambiguates duplicate heading text with a numeric suffix", () => {
    const toc = extractToc("## Overview\n\n## Overview\n");
    expect(toc.map((e) => e.slug)).toEqual(["overview", "overview-1"]);
  });

  it("ignores lines that only look like headings inside code fences (known limitation, documented not silently wrong)", () => {
    // This is a real limitation worth having a test pin down rather than
    // discover later: a naive line-regex scan doesn't know about fences.
    const withFence = "```\n# not a real heading\n```\n\n## Real heading\n";
    const toc = extractToc(withFence);
    expect(toc.map((e) => e.text)).toEqual(["not a real heading", "Real heading"]);
  });
});
